apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: allowedrolesv1
spec:
  crd:
    spec:
      names:
        kind: AllowedRolesV1
      validation:
        openAPIV3Schema:
          properties:
            roles:
              type: array
              items:
                type: string
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package allowedrolesv1

      allowedRoles(reviewRole) {
          roles := input.parameters.roles
          satisfied := [ good | role = roles[_]
                                good = lower(role) == lower(reviewRole)]
          any(satisfied)
      }

      violation[{"msg": msg}] {
          binding := input.review.object.spec.bindings[_]
          role := binding.role
          not allowedRoles(role)
          msg := sprintf("<%v> is disallowed, allowed roles are %v", [role, input.parameters.roles])
      }